name: Build Inside Official Rust 1.96.1 Docker Image
on:
  workflow_dispatch:
env:
  PROGRAM_ID: 3fN2LAt47q3oSgNq4dJZt4DuAh5yJw6mb6B3dRYJGHa8
jobs:
  build-in-docker:
    runs-on: ubuntu-latest
    container:
      image: rust:1.96.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Solana CLI 4.1.0-beta.3
        run: |
          apt-get update && apt-get install -y curl
          sh -c "$(curl -sSfL https://release.anza.xyz/v4.1.0-beta.3/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install anchor-cli 0.31.1 (newer patch, compatible with modern Rust)
        run: |
          cargo install --git https://github.com/solana-foundation/anchor anchor-cli --tag v0.31.1 --locked --force
          

      - name: Build
        run: |
          anchor build

          - name: Show generated IDL
        run: |
          cat target/idl/md1usd_solana.json

      - name: Upload IDL as artifact
        uses: actions/upload-artifact@v4
        with:
          name: md1usd_solana-idl
          path: target/idl/md1usd_solana.json

      - name: Get hash
        run: |
          sha256sum target/deploy/md1usd_solana.so
